//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYCVMAKERPROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int Id { get; set; }
        public string Ad_Name { get; set; }
        public int UserPageViews { get; set; }
        public int PersonalRegistration { get; set; }
        public int EmployersRegistration { get; set; }
        public int DailyViews { get; set; }
        public int TotalViews { get; set; }
        public int TotalJobAlerts { get; set; }
        public Nullable<int> UsersId { get; set; }
    
        public virtual User User { get; set; }
    }
}
