//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYCVMAKERPROJECT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CVMAKER_DBEntities : DbContext
    {
        public CVMAKER_DBEntities()
            : base("name=CVMAKER_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<CompanWorkExperience> CompanWorkExperiences { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyProject> CompanyProjects { get; set; }
        public virtual DbSet<CompanyService> CompanyServices { get; set; }
        public virtual DbSet<CompanySkill> CompanySkills { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<HitCounter> HitCounters { get; set; }
        public virtual DbSet<JobAlert> JobAlerts { get; set; }
        public virtual DbSet<Nofitication> Nofitications { get; set; }
        public virtual DbSet<Personal> Personals { get; set; }
        public virtual DbSet<PersonalProject> PersonalProjects { get; set; }
        public virtual DbSet<PersonalService> PersonalServices { get; set; }
        public virtual DbSet<PersonalSkill> PersonalSkills { get; set; }
        public virtual DbSet<PersonalWorkExperience> PersonalWorkExperiences { get; set; }
        public virtual DbSet<User> Users { get; set; }

        public System.Data.Entity.DbSet<MYCVMAKERPROJECT.Models.UsersMetaData> UsersMetaDatas { get; set; }
    }
}
