//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYCVMAKERPROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HitCounter
    {
        public int Id { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UsersId { get; set; }
    
        public virtual User User { get; set; }
    }
}
