//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYCVMAKERPROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalWorkExperience
    {
        public int Id { get; set; }
        public string City { get; set; }
        public string Employeer { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string Description { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> PersonalId { get; set; }
    
        public virtual Personal Personal { get; set; }
    }
}
